//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace LunarBase.Library.GameService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyChange", Namespace="http://schemas.datacontract.org/2004/07/LunarBase.WebData")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LunarBase.Library.GameService.Building))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LunarBase.Library.GameService.UserProfile))]
    public partial class PropertyChange : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Building", Namespace="http://schemas.datacontract.org/2004/07/LunarBase.WebData.Models")]
    public partial class Building : LunarBase.Library.GameService.PropertyChange {
        
        private int BuildsCompletedField;
        
        private int BuildsRequestedField;
        
        private string IdField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.ResourceInBuilding> ResourcesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuildsCompleted {
            get {
                return this.BuildsCompletedField;
            }
            set {
                if ((this.BuildsCompletedField.Equals(value) != true)) {
                    this.BuildsCompletedField = value;
                    this.RaisePropertyChanged("BuildsCompleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuildsRequested {
            get {
                return this.BuildsRequestedField;
            }
            set {
                if ((this.BuildsRequestedField.Equals(value) != true)) {
                    this.BuildsRequestedField = value;
                    this.RaisePropertyChanged("BuildsRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.ResourceInBuilding> Resources {
            get {
                return this.ResourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourcesField, value) != true)) {
                    this.ResourcesField = value;
                    this.RaisePropertyChanged("Resources");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/LunarBase.WebData.Models")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LunarBase.Library.GameService.PropertyChange))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LunarBase.Library.GameService.UsefullTypes))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LunarBase.Library.GameService.BuildingStatuses))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LunarBase.Library.GameService.City))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.BuildingInCity>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LunarBase.Library.GameService.BuildingInCity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LunarBase.Library.GameService.Building))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.ResourceInBuilding>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LunarBase.Library.GameService.ResourceInBuilding))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Building>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Race>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LunarBase.Library.GameService.Race))]
    public partial class UserProfile : LunarBase.Library.GameService.PropertyChange {
        
        private LunarBase.Library.GameService.City CityField;
        
        private string CityIdField;
        
        private string EmailField;
        
        private string IdField;
        
        private bool IsApprovedField;
        
        private object ProviderUserKeyField;
        
        private string RaceIdField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LunarBase.Library.GameService.City City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CityIdField, value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApproved {
            get {
                return this.IsApprovedField;
            }
            set {
                if ((this.IsApprovedField.Equals(value) != true)) {
                    this.IsApprovedField = value;
                    this.RaisePropertyChanged("IsApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ProviderUserKey {
            get {
                return this.ProviderUserKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderUserKeyField, value) != true)) {
                    this.ProviderUserKeyField = value;
                    this.RaisePropertyChanged("ProviderUserKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RaceId {
            get {
                return this.RaceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceIdField, value) != true)) {
                    this.RaceIdField = value;
                    this.RaisePropertyChanged("RaceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/LunarBase.WebData.Models")]
    public partial class City : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<string> BuildingInCityIdsField;
        
        private System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.BuildingInCity> BuildingsInCityField;
        
        private string IdField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> ResourceStorageIdsField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> UnitinCityIdsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<string> BuildingInCityIds {
            get {
                return this.BuildingInCityIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingInCityIdsField, value) != true)) {
                    this.BuildingInCityIdsField = value;
                    this.RaisePropertyChanged("BuildingInCityIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.BuildingInCity> BuildingsInCity {
            get {
                return this.BuildingsInCityField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingsInCityField, value) != true)) {
                    this.BuildingsInCityField = value;
                    this.RaisePropertyChanged("BuildingsInCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<string> ResourceStorageIds {
            get {
                return this.ResourceStorageIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceStorageIdsField, value) != true)) {
                    this.ResourceStorageIdsField = value;
                    this.RaisePropertyChanged("ResourceStorageIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<string> UnitinCityIds {
            get {
                return this.UnitinCityIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitinCityIdsField, value) != true)) {
                    this.UnitinCityIdsField = value;
                    this.RaisePropertyChanged("UnitinCityIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsefullTypes", Namespace="http://schemas.datacontract.org/2004/07/LunarBase.WebData")]
    public enum UsefullTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForBuilding = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForProduction = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Production = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuildingStatuses", Namespace="http://schemas.datacontract.org/2004/07/LunarBase.WebData")]
    public enum BuildingStatuses : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProduction = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Damaged = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InQuery = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuildingInCity", Namespace="http://schemas.datacontract.org/2004/07/LunarBase.WebData.Models")]
    public partial class BuildingInCity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LunarBase.Library.GameService.Building BuildingField;
        
        private string BuildingIdField;
        
        private string IdField;
        
        private LunarBase.Library.GameService.BuildingStatuses StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LunarBase.Library.GameService.Building Building {
            get {
                return this.BuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingField, value) != true)) {
                    this.BuildingField = value;
                    this.RaisePropertyChanged("Building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingId {
            get {
                return this.BuildingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingIdField, value) != true)) {
                    this.BuildingIdField = value;
                    this.RaisePropertyChanged("BuildingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LunarBase.Library.GameService.BuildingStatuses Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceInBuilding", Namespace="http://schemas.datacontract.org/2004/07/LunarBase.WebData.Models")]
    public partial class ResourceInBuilding : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string IdField;
        
        private int ProducePerTurnField;
        
        private string ResourceIdField;
        
        private LunarBase.Library.GameService.UsefullTypes UsefullTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProducePerTurn {
            get {
                return this.ProducePerTurnField;
            }
            set {
                if ((this.ProducePerTurnField.Equals(value) != true)) {
                    this.ProducePerTurnField = value;
                    this.RaisePropertyChanged("ProducePerTurn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceId {
            get {
                return this.ResourceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceIdField, value) != true)) {
                    this.ResourceIdField = value;
                    this.RaisePropertyChanged("ResourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LunarBase.Library.GameService.UsefullTypes UsefullType {
            get {
                return this.UsefullTypeField;
            }
            set {
                if ((this.UsefullTypeField.Equals(value) != true)) {
                    this.UsefullTypeField = value;
                    this.RaisePropertyChanged("UsefullType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Race", Namespace="http://schemas.datacontract.org/2004/07/LunarBase.WebData.Models")]
    public partial class Race : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BonusField;
        
        private string IdField;
        
        private string NameField;
        
        private string PictureUriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bonus {
            get {
                return this.BonusField;
            }
            set {
                if ((object.ReferenceEquals(this.BonusField, value) != true)) {
                    this.BonusField = value;
                    this.RaisePropertyChanged("Bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PictureUri {
            get {
                return this.PictureUriField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureUriField, value) != true)) {
                    this.PictureUriField = value;
                    this.RaisePropertyChanged("PictureUri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="GameService", ConfigurationName="GameService.GameService")]
    public interface GameService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GameService/GameService/Login", ReplyAction="GameService/GameService/LoginResponse")]
        System.IAsyncResult BeginLogin(string email, string password, System.AsyncCallback callback, object asyncState);
        
        LunarBase.Library.GameService.UserProfile EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GameService/GameService/GetCity", ReplyAction="GameService/GameService/GetCityResponse")]
        System.IAsyncResult BeginGetCity(string authToken, string cityId, System.AsyncCallback callback, object asyncState);
        
        LunarBase.Library.GameService.City EndGetCity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GameService/GameService/SaveBuilding", ReplyAction="GameService/GameService/SaveBuildingResponse")]
        System.IAsyncResult BeginSaveBuilding(string authToken, LunarBase.Library.GameService.Building building, System.AsyncCallback callback, object asyncState);
        
        LunarBase.Library.GameService.Building EndSaveBuilding(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GameService/GameService/GetBuildings", ReplyAction="GameService/GameService/GetBuildingsResponse")]
        System.IAsyncResult BeginGetBuildings(string authToken, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Building> EndGetBuildings(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GameService/GameService/SaveBuildingInCity", ReplyAction="GameService/GameService/SaveBuildingInCityResponse")]
        System.IAsyncResult BeginSaveBuildingInCity(string authToken, LunarBase.Library.GameService.BuildingInCity buildingInCity, System.AsyncCallback callback, object asyncState);
        
        bool EndSaveBuildingInCity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GameService/GameService/SaveCity", ReplyAction="GameService/GameService/SaveCityResponse")]
        System.IAsyncResult BeginSaveCity(string authToken, LunarBase.Library.GameService.City city, System.AsyncCallback callback, object asyncState);
        
        bool EndSaveCity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GameService/GameService/SaveUserProfile", ReplyAction="GameService/GameService/SaveUserProfileResponse")]
        System.IAsyncResult BeginSaveUserProfile(string authToken, LunarBase.Library.GameService.UserProfile userProfile, System.AsyncCallback callback, object asyncState);
        
        LunarBase.Library.GameService.UserProfile EndSaveUserProfile(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="GameService/GameService/GetRaces", ReplyAction="GameService/GameService/GetRacesResponse")]
        System.IAsyncResult BeginGetRaces(string authToken, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Race> EndGetRaces(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GameServiceChannel : LunarBase.Library.GameService.GameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LunarBase.Library.GameService.UserProfile Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LunarBase.Library.GameService.UserProfile)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LunarBase.Library.GameService.City Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LunarBase.Library.GameService.City)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveBuildingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveBuildingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LunarBase.Library.GameService.Building Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LunarBase.Library.GameService.Building)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBuildingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBuildingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Building> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Building>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveBuildingInCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveBuildingInCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveUserProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveUserProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LunarBase.Library.GameService.UserProfile Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LunarBase.Library.GameService.UserProfile)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRacesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRacesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Race> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Race>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.ClientBase<LunarBase.Library.GameService.GameService>, LunarBase.Library.GameService.GameService {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCityDelegate;
        
        private EndOperationDelegate onEndGetCityDelegate;
        
        private System.Threading.SendOrPostCallback onGetCityCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveBuildingDelegate;
        
        private EndOperationDelegate onEndSaveBuildingDelegate;
        
        private System.Threading.SendOrPostCallback onSaveBuildingCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetBuildingsDelegate;
        
        private EndOperationDelegate onEndGetBuildingsDelegate;
        
        private System.Threading.SendOrPostCallback onGetBuildingsCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveBuildingInCityDelegate;
        
        private EndOperationDelegate onEndSaveBuildingInCityDelegate;
        
        private System.Threading.SendOrPostCallback onSaveBuildingInCityCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveCityDelegate;
        
        private EndOperationDelegate onEndSaveCityDelegate;
        
        private System.Threading.SendOrPostCallback onSaveCityCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveUserProfileDelegate;
        
        private EndOperationDelegate onEndSaveUserProfileDelegate;
        
        private System.Threading.SendOrPostCallback onSaveUserProfileCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRacesDelegate;
        
        private EndOperationDelegate onEndGetRacesDelegate;
        
        private System.Threading.SendOrPostCallback onGetRacesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public GameServiceClient() {
        }
        
        public GameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<GetCityCompletedEventArgs> GetCityCompleted;
        
        public event System.EventHandler<SaveBuildingCompletedEventArgs> SaveBuildingCompleted;
        
        public event System.EventHandler<GetBuildingsCompletedEventArgs> GetBuildingsCompleted;
        
        public event System.EventHandler<SaveBuildingInCityCompletedEventArgs> SaveBuildingInCityCompleted;
        
        public event System.EventHandler<SaveCityCompletedEventArgs> SaveCityCompleted;
        
        public event System.EventHandler<SaveUserProfileCompletedEventArgs> SaveUserProfileCompleted;
        
        public event System.EventHandler<GetRacesCompletedEventArgs> GetRacesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LunarBase.Library.GameService.GameService.BeginLogin(string email, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(email, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LunarBase.Library.GameService.UserProfile LunarBase.Library.GameService.GameService.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((LunarBase.Library.GameService.GameService)(this)).BeginLogin(email, password, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            LunarBase.Library.GameService.UserProfile retVal = ((LunarBase.Library.GameService.GameService)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string email, string password) {
            this.LoginAsync(email, password, null);
        }
        
        public void LoginAsync(string email, string password, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        email,
                        password}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LunarBase.Library.GameService.GameService.BeginGetCity(string authToken, string cityId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCity(authToken, cityId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LunarBase.Library.GameService.City LunarBase.Library.GameService.GameService.EndGetCity(System.IAsyncResult result) {
            return base.Channel.EndGetCity(result);
        }
        
        private System.IAsyncResult OnBeginGetCity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string authToken = ((string)(inValues[0]));
            string cityId = ((string)(inValues[1]));
            return ((LunarBase.Library.GameService.GameService)(this)).BeginGetCity(authToken, cityId, callback, asyncState);
        }
        
        private object[] OnEndGetCity(System.IAsyncResult result) {
            LunarBase.Library.GameService.City retVal = ((LunarBase.Library.GameService.GameService)(this)).EndGetCity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCityCompleted(object state) {
            if ((this.GetCityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCityCompleted(this, new GetCityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCityAsync(string authToken, string cityId) {
            this.GetCityAsync(authToken, cityId, null);
        }
        
        public void GetCityAsync(string authToken, string cityId, object userState) {
            if ((this.onBeginGetCityDelegate == null)) {
                this.onBeginGetCityDelegate = new BeginOperationDelegate(this.OnBeginGetCity);
            }
            if ((this.onEndGetCityDelegate == null)) {
                this.onEndGetCityDelegate = new EndOperationDelegate(this.OnEndGetCity);
            }
            if ((this.onGetCityCompletedDelegate == null)) {
                this.onGetCityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCityCompleted);
            }
            base.InvokeAsync(this.onBeginGetCityDelegate, new object[] {
                        authToken,
                        cityId}, this.onEndGetCityDelegate, this.onGetCityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LunarBase.Library.GameService.GameService.BeginSaveBuilding(string authToken, LunarBase.Library.GameService.Building building, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveBuilding(authToken, building, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LunarBase.Library.GameService.Building LunarBase.Library.GameService.GameService.EndSaveBuilding(System.IAsyncResult result) {
            return base.Channel.EndSaveBuilding(result);
        }
        
        private System.IAsyncResult OnBeginSaveBuilding(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string authToken = ((string)(inValues[0]));
            LunarBase.Library.GameService.Building building = ((LunarBase.Library.GameService.Building)(inValues[1]));
            return ((LunarBase.Library.GameService.GameService)(this)).BeginSaveBuilding(authToken, building, callback, asyncState);
        }
        
        private object[] OnEndSaveBuilding(System.IAsyncResult result) {
            LunarBase.Library.GameService.Building retVal = ((LunarBase.Library.GameService.GameService)(this)).EndSaveBuilding(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveBuildingCompleted(object state) {
            if ((this.SaveBuildingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveBuildingCompleted(this, new SaveBuildingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveBuildingAsync(string authToken, LunarBase.Library.GameService.Building building) {
            this.SaveBuildingAsync(authToken, building, null);
        }
        
        public void SaveBuildingAsync(string authToken, LunarBase.Library.GameService.Building building, object userState) {
            if ((this.onBeginSaveBuildingDelegate == null)) {
                this.onBeginSaveBuildingDelegate = new BeginOperationDelegate(this.OnBeginSaveBuilding);
            }
            if ((this.onEndSaveBuildingDelegate == null)) {
                this.onEndSaveBuildingDelegate = new EndOperationDelegate(this.OnEndSaveBuilding);
            }
            if ((this.onSaveBuildingCompletedDelegate == null)) {
                this.onSaveBuildingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveBuildingCompleted);
            }
            base.InvokeAsync(this.onBeginSaveBuildingDelegate, new object[] {
                        authToken,
                        building}, this.onEndSaveBuildingDelegate, this.onSaveBuildingCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LunarBase.Library.GameService.GameService.BeginGetBuildings(string authToken, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBuildings(authToken, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Building> LunarBase.Library.GameService.GameService.EndGetBuildings(System.IAsyncResult result) {
            return base.Channel.EndGetBuildings(result);
        }
        
        private System.IAsyncResult OnBeginGetBuildings(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string authToken = ((string)(inValues[0]));
            return ((LunarBase.Library.GameService.GameService)(this)).BeginGetBuildings(authToken, callback, asyncState);
        }
        
        private object[] OnEndGetBuildings(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Building> retVal = ((LunarBase.Library.GameService.GameService)(this)).EndGetBuildings(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBuildingsCompleted(object state) {
            if ((this.GetBuildingsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBuildingsCompleted(this, new GetBuildingsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBuildingsAsync(string authToken) {
            this.GetBuildingsAsync(authToken, null);
        }
        
        public void GetBuildingsAsync(string authToken, object userState) {
            if ((this.onBeginGetBuildingsDelegate == null)) {
                this.onBeginGetBuildingsDelegate = new BeginOperationDelegate(this.OnBeginGetBuildings);
            }
            if ((this.onEndGetBuildingsDelegate == null)) {
                this.onEndGetBuildingsDelegate = new EndOperationDelegate(this.OnEndGetBuildings);
            }
            if ((this.onGetBuildingsCompletedDelegate == null)) {
                this.onGetBuildingsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBuildingsCompleted);
            }
            base.InvokeAsync(this.onBeginGetBuildingsDelegate, new object[] {
                        authToken}, this.onEndGetBuildingsDelegate, this.onGetBuildingsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LunarBase.Library.GameService.GameService.BeginSaveBuildingInCity(string authToken, LunarBase.Library.GameService.BuildingInCity buildingInCity, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveBuildingInCity(authToken, buildingInCity, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool LunarBase.Library.GameService.GameService.EndSaveBuildingInCity(System.IAsyncResult result) {
            return base.Channel.EndSaveBuildingInCity(result);
        }
        
        private System.IAsyncResult OnBeginSaveBuildingInCity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string authToken = ((string)(inValues[0]));
            LunarBase.Library.GameService.BuildingInCity buildingInCity = ((LunarBase.Library.GameService.BuildingInCity)(inValues[1]));
            return ((LunarBase.Library.GameService.GameService)(this)).BeginSaveBuildingInCity(authToken, buildingInCity, callback, asyncState);
        }
        
        private object[] OnEndSaveBuildingInCity(System.IAsyncResult result) {
            bool retVal = ((LunarBase.Library.GameService.GameService)(this)).EndSaveBuildingInCity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveBuildingInCityCompleted(object state) {
            if ((this.SaveBuildingInCityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveBuildingInCityCompleted(this, new SaveBuildingInCityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveBuildingInCityAsync(string authToken, LunarBase.Library.GameService.BuildingInCity buildingInCity) {
            this.SaveBuildingInCityAsync(authToken, buildingInCity, null);
        }
        
        public void SaveBuildingInCityAsync(string authToken, LunarBase.Library.GameService.BuildingInCity buildingInCity, object userState) {
            if ((this.onBeginSaveBuildingInCityDelegate == null)) {
                this.onBeginSaveBuildingInCityDelegate = new BeginOperationDelegate(this.OnBeginSaveBuildingInCity);
            }
            if ((this.onEndSaveBuildingInCityDelegate == null)) {
                this.onEndSaveBuildingInCityDelegate = new EndOperationDelegate(this.OnEndSaveBuildingInCity);
            }
            if ((this.onSaveBuildingInCityCompletedDelegate == null)) {
                this.onSaveBuildingInCityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveBuildingInCityCompleted);
            }
            base.InvokeAsync(this.onBeginSaveBuildingInCityDelegate, new object[] {
                        authToken,
                        buildingInCity}, this.onEndSaveBuildingInCityDelegate, this.onSaveBuildingInCityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LunarBase.Library.GameService.GameService.BeginSaveCity(string authToken, LunarBase.Library.GameService.City city, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveCity(authToken, city, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool LunarBase.Library.GameService.GameService.EndSaveCity(System.IAsyncResult result) {
            return base.Channel.EndSaveCity(result);
        }
        
        private System.IAsyncResult OnBeginSaveCity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string authToken = ((string)(inValues[0]));
            LunarBase.Library.GameService.City city = ((LunarBase.Library.GameService.City)(inValues[1]));
            return ((LunarBase.Library.GameService.GameService)(this)).BeginSaveCity(authToken, city, callback, asyncState);
        }
        
        private object[] OnEndSaveCity(System.IAsyncResult result) {
            bool retVal = ((LunarBase.Library.GameService.GameService)(this)).EndSaveCity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveCityCompleted(object state) {
            if ((this.SaveCityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveCityCompleted(this, new SaveCityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveCityAsync(string authToken, LunarBase.Library.GameService.City city) {
            this.SaveCityAsync(authToken, city, null);
        }
        
        public void SaveCityAsync(string authToken, LunarBase.Library.GameService.City city, object userState) {
            if ((this.onBeginSaveCityDelegate == null)) {
                this.onBeginSaveCityDelegate = new BeginOperationDelegate(this.OnBeginSaveCity);
            }
            if ((this.onEndSaveCityDelegate == null)) {
                this.onEndSaveCityDelegate = new EndOperationDelegate(this.OnEndSaveCity);
            }
            if ((this.onSaveCityCompletedDelegate == null)) {
                this.onSaveCityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveCityCompleted);
            }
            base.InvokeAsync(this.onBeginSaveCityDelegate, new object[] {
                        authToken,
                        city}, this.onEndSaveCityDelegate, this.onSaveCityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LunarBase.Library.GameService.GameService.BeginSaveUserProfile(string authToken, LunarBase.Library.GameService.UserProfile userProfile, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveUserProfile(authToken, userProfile, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LunarBase.Library.GameService.UserProfile LunarBase.Library.GameService.GameService.EndSaveUserProfile(System.IAsyncResult result) {
            return base.Channel.EndSaveUserProfile(result);
        }
        
        private System.IAsyncResult OnBeginSaveUserProfile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string authToken = ((string)(inValues[0]));
            LunarBase.Library.GameService.UserProfile userProfile = ((LunarBase.Library.GameService.UserProfile)(inValues[1]));
            return ((LunarBase.Library.GameService.GameService)(this)).BeginSaveUserProfile(authToken, userProfile, callback, asyncState);
        }
        
        private object[] OnEndSaveUserProfile(System.IAsyncResult result) {
            LunarBase.Library.GameService.UserProfile retVal = ((LunarBase.Library.GameService.GameService)(this)).EndSaveUserProfile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveUserProfileCompleted(object state) {
            if ((this.SaveUserProfileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveUserProfileCompleted(this, new SaveUserProfileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveUserProfileAsync(string authToken, LunarBase.Library.GameService.UserProfile userProfile) {
            this.SaveUserProfileAsync(authToken, userProfile, null);
        }
        
        public void SaveUserProfileAsync(string authToken, LunarBase.Library.GameService.UserProfile userProfile, object userState) {
            if ((this.onBeginSaveUserProfileDelegate == null)) {
                this.onBeginSaveUserProfileDelegate = new BeginOperationDelegate(this.OnBeginSaveUserProfile);
            }
            if ((this.onEndSaveUserProfileDelegate == null)) {
                this.onEndSaveUserProfileDelegate = new EndOperationDelegate(this.OnEndSaveUserProfile);
            }
            if ((this.onSaveUserProfileCompletedDelegate == null)) {
                this.onSaveUserProfileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveUserProfileCompleted);
            }
            base.InvokeAsync(this.onBeginSaveUserProfileDelegate, new object[] {
                        authToken,
                        userProfile}, this.onEndSaveUserProfileDelegate, this.onSaveUserProfileCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LunarBase.Library.GameService.GameService.BeginGetRaces(string authToken, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRaces(authToken, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Race> LunarBase.Library.GameService.GameService.EndGetRaces(System.IAsyncResult result) {
            return base.Channel.EndGetRaces(result);
        }
        
        private System.IAsyncResult OnBeginGetRaces(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string authToken = ((string)(inValues[0]));
            return ((LunarBase.Library.GameService.GameService)(this)).BeginGetRaces(authToken, callback, asyncState);
        }
        
        private object[] OnEndGetRaces(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Race> retVal = ((LunarBase.Library.GameService.GameService)(this)).EndGetRaces(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRacesCompleted(object state) {
            if ((this.GetRacesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRacesCompleted(this, new GetRacesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRacesAsync(string authToken) {
            this.GetRacesAsync(authToken, null);
        }
        
        public void GetRacesAsync(string authToken, object userState) {
            if ((this.onBeginGetRacesDelegate == null)) {
                this.onBeginGetRacesDelegate = new BeginOperationDelegate(this.OnBeginGetRaces);
            }
            if ((this.onEndGetRacesDelegate == null)) {
                this.onEndGetRacesDelegate = new EndOperationDelegate(this.OnEndGetRaces);
            }
            if ((this.onGetRacesCompletedDelegate == null)) {
                this.onGetRacesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRacesCompleted);
            }
            base.InvokeAsync(this.onBeginGetRacesDelegate, new object[] {
                        authToken}, this.onEndGetRacesDelegate, this.onGetRacesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override LunarBase.Library.GameService.GameService CreateChannel() {
            return new GameServiceClientChannel(this);
        }
        
        private class GameServiceClientChannel : ChannelBase<LunarBase.Library.GameService.GameService>, LunarBase.Library.GameService.GameService {
            
            public GameServiceClientChannel(System.ServiceModel.ClientBase<LunarBase.Library.GameService.GameService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogin(string email, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = email;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public LunarBase.Library.GameService.UserProfile EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                LunarBase.Library.GameService.UserProfile _result = ((LunarBase.Library.GameService.UserProfile)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCity(string authToken, string cityId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = authToken;
                _args[1] = cityId;
                System.IAsyncResult _result = base.BeginInvoke("GetCity", _args, callback, asyncState);
                return _result;
            }
            
            public LunarBase.Library.GameService.City EndGetCity(System.IAsyncResult result) {
                object[] _args = new object[0];
                LunarBase.Library.GameService.City _result = ((LunarBase.Library.GameService.City)(base.EndInvoke("GetCity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveBuilding(string authToken, LunarBase.Library.GameService.Building building, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = authToken;
                _args[1] = building;
                System.IAsyncResult _result = base.BeginInvoke("SaveBuilding", _args, callback, asyncState);
                return _result;
            }
            
            public LunarBase.Library.GameService.Building EndSaveBuilding(System.IAsyncResult result) {
                object[] _args = new object[0];
                LunarBase.Library.GameService.Building _result = ((LunarBase.Library.GameService.Building)(base.EndInvoke("SaveBuilding", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetBuildings(string authToken, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = authToken;
                System.IAsyncResult _result = base.BeginInvoke("GetBuildings", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Building> EndGetBuildings(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Building> _result = ((System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Building>)(base.EndInvoke("GetBuildings", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveBuildingInCity(string authToken, LunarBase.Library.GameService.BuildingInCity buildingInCity, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = authToken;
                _args[1] = buildingInCity;
                System.IAsyncResult _result = base.BeginInvoke("SaveBuildingInCity", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndSaveBuildingInCity(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("SaveBuildingInCity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveCity(string authToken, LunarBase.Library.GameService.City city, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = authToken;
                _args[1] = city;
                System.IAsyncResult _result = base.BeginInvoke("SaveCity", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndSaveCity(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("SaveCity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveUserProfile(string authToken, LunarBase.Library.GameService.UserProfile userProfile, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = authToken;
                _args[1] = userProfile;
                System.IAsyncResult _result = base.BeginInvoke("SaveUserProfile", _args, callback, asyncState);
                return _result;
            }
            
            public LunarBase.Library.GameService.UserProfile EndSaveUserProfile(System.IAsyncResult result) {
                object[] _args = new object[0];
                LunarBase.Library.GameService.UserProfile _result = ((LunarBase.Library.GameService.UserProfile)(base.EndInvoke("SaveUserProfile", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRaces(string authToken, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = authToken;
                System.IAsyncResult _result = base.BeginInvoke("GetRaces", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Race> EndGetRaces(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Race> _result = ((System.Collections.ObjectModel.ObservableCollection<LunarBase.Library.GameService.Race>)(base.EndInvoke("GetRaces", _args, result)));
                return _result;
            }
        }
    }
}
